### ISSUE TITLE
stops after selecting health

### ISSUE THREAD

**Issue by scrybeofteeth** [IngoHHacks/IGCCMod#6] opened 2022-03-20 05:04 UTC
[Error  : Unity Log] MissingFieldException: Field 'APIPlugin.NewAbility.abilities' not found.
Stack trace:
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <3f8c35799b544274b189c23afcaaf82e>:0)

the game soft locks me with me facing the cards, but the cards for abilities never show up.

**Comment by IngoHHacks** [comment] 2022-03-20 10:02
Caused by the Kaycee's Mod update. Will be fixed soon.

**Closed as completed** 2022-03-26 14:23 UTC
